apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  name: olm-kubecon2025-demo
spec:
  source:
    type: Image
    image:
      ref: kind-registry:5443/olm-kubecon2025-demo:catalog
      pollIntervalMinutes: 1
