---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: demo-operator
spec:
  namespace: demo-operator
  serviceAccount:
    name: demo-operator-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: demo-operator
      version: 0.0.1
  config:
    configType: Inline
    inline:
      watchNamespace: demo
