---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: demo-operator
spec:
  namespace: demo-operator
  serviceAccount:
    name: demo-operator-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: demo-operator
      version: 0.0.2
  config:
    configType: Inline
    inline:
      watchNamespace: demo
  install:
    preflight:
      crdUpgradeSafety:
        enforcement: None
